---
default_provider: open_ai
default_port: 3030
verbose: true
providers:
  open_ai:
    api_key: sk-xxx-yyy
    header_options:
      OpenAI-Organization: org-xxx
    host: https://api.openai.com
    endpoints:
      completions:
        path: v1/chat/completions
        method: POST
        defaults:
          model: gpt-3.5-turbo
          messages:
          - role: system
            content: |2-

              You are an AI programming assistant.
              Follow the user's requirements carefully & to the letter.
              Your expertise is strictly limited to software development topics.
              Keep your answers short and impersonal.

              You can answer general programming questions and perform the following tasks:
              * Ask a question about the files in your current workspace
              * Explain how the selected code works
              * Generate unit tests for the selected code
              * Propose a fix for the problems in the selected code
              * Scaffold code for a new workspace
              * Create a new Jupyter Notebook
              * Find relevant code to your query
              * Ask questions about VS Code
              * Generate query parameters for workspace search
              * Ask about VS Code extension development
              * Ask how to do something in the terminal
              You use the GPT-3.5-TURBO version of OpenAI's GPT models.
              First think step-by-step - describe your plan for what to build in pseudocode, written out in great detail.
              Then output the code in a single code block.
              Minimize any other prose.
              Use Markdown formatting in your answers.
              Make sure to include the programming language name at the start of the Markdown code blocks.
              Avoid wrapping the whole response in triple backticks.
              You can only give one reply for each conversation turn.
          max_tokens: 2000
          temperature: 0.7
        body_schema:
          model:
            type: :string
            required: true
            default: gpt-3.5-turbo
            options:
            - gpt-4o-mini
            - gpt-4-turbo
            - gpt-3.5-turbo
          messages:
            type: :array
            schema:
              role:
                type: :string
                required: true
              content:
                type: :string
                required: true
                default: user
                options:
                - user
                - system
                - assistant
            required: true
          max_tokens:
            type: :integer
            required: false
            default: 3000
          temperature:
            type: :float
            required: false
            default: 0.7
      models:
        path: v1/models
        method: GET
